# This rule is not used by the project qubesec itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the qubesec.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: qubesec
    app.kubernetes.io/managed-by: kustomize
  name: quantumdecapsulatesecret-editor-role
rules:
- apiGroups:
  - qubesec.io
  resources:
  - quantumdecapsulatesecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qubesec.io
  resources:
  - quantumdecapsulatesecrets/status
  verbs:
  - get
