apiVersion: qubesec.io/v1
kind: QuantumSignatureKeyPair
metadata:
  labels:
    app.kubernetes.io/name: quantumsignaturekeypair
    app.kubernetes.io/instance: quantumsignaturekeypair-sample
    app.kubernetes.io/part-of: qubesec
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: qubesec
  name: quantumsignaturekeypair-sample
spec:
  algorithm: ML-DSA-87
  # Optional custom secret name for the generated key pair
  secretName: quantumsignaturekeypair-sample-keys
