apiVersion: qubesec.io/v1
kind: QuantumCertificate
metadata:
  labels:
    app.kubernetes.io/name: quantumcertificate
    app.kubernetes.io/instance: quantumcertificate-sample
    app.kubernetes.io/part-of: qubesec
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: qubesec
  name: quantumcertificate-sample
spec:
  algorithm: "ML-DSA-87"
  # algorithm: "rsa"
  domain: "example.com"
  days: 365
  # Optional custom secret name for the certificate (tls.crt/tls.key)
  secretName: quantumcertificate-sample-cert
