apiVersion: qubesec.io/v1
kind: QuantumKEMKeyPair
metadata:
  labels:
    app.kubernetes.io/name: quantumkemkeypair
    app.kubernetes.io/instance: quantumkemkeypair-sample
    app.kubernetes.io/part-of: qubesec
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: qubesec
  name: quantumkemkeypair-sample
spec:
  algorithm: ML-KEM-1024
  # Optional custom secret name for the generated key pair
  secretName: quantumkemkeypair-sample-keys
