## Append samples of your project ##
resources:
- _v1_quantumrandomnumber.yaml
- _v1_quantumkemkeypair.yaml
- _v1_quantumsignaturekeypair.yaml
- _v1_quantumcertificate.yaml
- _v1_quantumsharedsecret.yaml
- _v1_quantumderivedkey.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
