apiVersion: qubesec.io/v1
kind: QuantumSharedSecret
metadata:
  labels:
    app.kubernetes.io/name: qubesec
    app.kubernetes.io/managed-by: kustomize
  name: quantumsharedsecret-sample
spec:
  # TODO(user): Add fields here
