# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/qubesec.io_quantumrandomnumbers.yaml
- bases/qubesec.io_quantumkemkeypairs.yaml
- bases/qubesec.io_quantumsignaturekeypairs.yaml
- bases/qubesec.io_quantumcertificates.yaml
- bases/qubesec.io_quantumencapsulatesecrets.yaml
- bases/qubesec.io_quantumdecapsulatesecrets.yaml
- bases/qubesec.io_quantumderivedkeys.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_quantumrandomnumbers.yaml
#- path: patches/webhook_in_quantumkemkeypairs.yaml
#- path: patches/webhook_in_quantumsignaturekeypairs.yaml
#- path: patches/webhook_in_quantumcertificates.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_quantumrandomnumbers.yaml
#- path: patches/cainjection_in_quantumkemkeypairs.yaml
#- path: patches/cainjection_in_quantumsignaturekeypairs.yaml
#- path: patches/cainjection_in_quantumcertificates.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

configurations:
- kustomizeconfig.yaml
