---
- name: Setup liboqs
  hosts: all
  roles:
    - role: docker
    - role: minikube
    - role: kubectl
    - role: golang
    - role: liboqs-go
    - role: liboqs
    - role: openssl
    - role: oqs-provider
  vars:
    liboqs_version: "0.15.0"
    liboqs_go_version: "0.12.0"
    oqs_provider_version: "0.11.0"
    openssl_version: "3.6.0"
